version: "3.5"

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    image: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - cse_platform

networks:
  cse_platform:
    name: cse_platform
    external: true